In [69]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [70]:
df = pd.read_csv("medical data.csv")

In [71]:
df

,Name,DateOfBirth,Gender,Symptoms,Causes,Disease,Medicine
0,John Doe,15-05-1980,Male,"Fever, Cough",Viral Infection,Common Cold,"Ibuprofen, Rest"
1,Jane Smith,10-08-1992,Female,"Headache, Fatigue",Stress,Migraine,Sumatriptan
2,Michael Lee,20-02-1975,Male,Shortness of breath,Pollution,Asthma,Albuterol Inhaler
3,Emily Chen,03-11-1988,Female,"Nausea, Vomiting",Food Poisoning,Gastroenteritis,Oral Rehydration
4,Alex Wong,12-06-2001,Male,Sore Throat,Bacterial Infection,Strep Throat,Penicillin
...,...,...,...,...,...,...,...
282,Ava Lim,11-07-1993,Female,"Cough, Shortness of breath",COVID-19 Exposure,COVID-19,"Isolation, Fluids"
283,Liam Goh,16-09-1987,Male,"Itching, Redness",Allergies,Allergic Reaction An,tihistamine
284,Sophie Tan,18-02-1975,Female,"Muscle Pain, Fatigue",Overexertion,Muscle Strain,"Rest, Pain Relievers"
285,Noah Lim,21-05-2005,Male,"Nausea, Vomiting",Food Poisoning,Muscle Strain,Rehydration
286,Ella Wong,05-10-1999,Female,"Headache, Blurred Vision",Eye Strain,Muscle Strain,Eye Exercises

In [72]:
df.shape

(287, 7)

In [73]:
df.columns

Index(['Name', 'DateOfBirth', 'Gender', 'Symptoms', 'Causes', 'Disease',
       'Medicine'],
      dtype='str')

In [74]:
df.dtypes

Name           str
DateOfBirth    str
Gender         str
Symptoms       str
Causes         str
Disease        str
Medicine       str
dtype: object

In [75]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 287 entries, 0 to 286
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         241 non-null    str
 1   DateOfBirth  241 non-null    str
 2   Gender       242 non-null    str
 3   Symptoms     247 non-null    str
 4   Causes       245 non-null    str
 5   Disease      249 non-null    str
 6   Medicine     242 non-null    str
dtypes: str(7)
memory usage: 15.8 KB

In [76]:
df.describe()

,Name,DateOfBirth,Gender,Symptoms,Causes,Disease,Medicine
count,241,241,242,247,245,249,242
unique,87,98,4,53,62,68,65
top,Sophia Koh,18-02-1975,Male,"Fatigue, Weakness",Food Poisoning,Gastroenteritis,"Rest, Lifestyle"
freq,9,8,116,19,20,20,16

In [77]:
df.isnull().sum()

Name           46
DateOfBirth    46
Gender         45
Symptoms       40
Causes         42
Disease        38
Medicine       45
dtype: int64

In [78]:
df.isnull().sum().sum()

np.int64(302)

In [79]:
df.duplicated().sum()

np.int64(122)

In [80]:
df = df.dropna(how="all")

In [81]:
df

,Name,DateOfBirth,Gender,Symptoms,Causes,Disease,Medicine
0,John Doe,15-05-1980,Male,"Fever, Cough",Viral Infection,Common Cold,"Ibuprofen, Rest"
1,Jane Smith,10-08-1992,Female,"Headache, Fatigue",Stress,Migraine,Sumatriptan
2,Michael Lee,20-02-1975,Male,Shortness of breath,Pollution,Asthma,Albuterol Inhaler
3,Emily Chen,03-11-1988,Female,"Nausea, Vomiting",Food Poisoning,Gastroenteritis,Oral Rehydration
4,Alex Wong,12-06-2001,Male,Sore Throat,Bacterial Infection,Strep Throat,Penicillin
...,...,...,...,...,...,...,...
282,Ava Lim,11-07-1993,Female,"Cough, Shortness of breath",COVID-19 Exposure,COVID-19,"Isolation, Fluids"
283,Liam Goh,16-09-1987,Male,"Itching, Redness",Allergies,Allergic Reaction An,tihistamine
284,Sophie Tan,18-02-1975,Female,"Muscle Pain, Fatigue",Overexertion,Muscle Strain,"Rest, Pain Relievers"
285,Noah Lim,21-05-2005,Male,"Nausea, Vomiting",Food Poisoning,Muscle Strain,Rehydration
286,Ella Wong,05-10-1999,Female,"Headache, Blurred Vision",Eye Strain,Muscle Strain,Eye Exercises

In [82]:
df.columns = df.columns.str.strip()

In [83]:
text_columns = df.select_dtypes(include="object").columns

In [84]:
for col in text_columns:
    df[col] = df[col].str.strip()

In [85]:
df.head()

,Name,DateOfBirth,Gender,Symptoms,Causes,Disease,Medicine
0,John Doe,15-05-1980,Male,"Fever, Cough",Viral Infection,Common Cold,"Ibuprofen, Rest"
1,Jane Smith,10-08-1992,Female,"Headache, Fatigue",Stress,Migraine,Sumatriptan
2,Michael Lee,20-02-1975,Male,Shortness of breath,Pollution,Asthma,Albuterol Inhaler
3,Emily Chen,03-11-1988,Female,"Nausea, Vomiting",Food Poisoning,Gastroenteritis,Oral Rehydration
4,Alex Wong,12-06-2001,Male,Sore Throat,Bacterial Infection,Strep Throat,Penicillin

In [86]:
df["Name"] = df["Name"].fillna(df["Name"].mode()[0],inplace=True)

In [87]:
df["Gender"]=df["Gender"].fillna(df["Gender"].mode()[0],inplace=True)

In [88]:
df["Symptoms"]=df["Symptoms"].fillna(df["Symptoms"].mode()[0],inplace=True)

In [89]:
df["Causes"]=df["Causes"].fillna(df["Causes"].mode()[0],inplace=True)

In [90]:
df["Disease"]=df["Disease"].fillna(df["Disease"].mode()[0],inplace=True)

In [91]:
df["Medicine"]=df["Medicine"].fillna(df["Medicine"].mode()[0],inplace=True)

In [92]:
df.isnull().sum()

Name            0
DateOfBirth    13
Gender          0
Symptoms        0
Causes          0
Disease         0
Medicine        0
dtype: int64

In [93]:
df = df.drop_duplicates()

In [94]:
df.duplicated().sum()

np.int64(0)

In [95]:
df["DateOfBirth"] = df["DateOfBirth"].fillna(df["DateOfBirth"].mode()[0],inplace=True)

In [96]:
df.isnull().sum().sum()

np.int64(0)

In [97]:
df=df.reset_index(drop=True)

In [98]:
df.head(10)

,Name,DateOfBirth,Gender,Symptoms,Causes,Disease,Medicine
0,John Doe,15-05-1980,Male,"Fever, Cough",Viral Infection,Common Cold,"Ibuprofen, Rest"
1,Jane Smith,10-08-1992,Female,"Headache, Fatigue",Stress,Migraine,Sumatriptan
2,Michael Lee,20-02-1975,Male,Shortness of breath,Pollution,Asthma,Albuterol Inhaler
3,Emily Chen,03-11-1988,Female,"Nausea, Vomiting",Food Poisoning,Gastroenteritis,Oral Rehydration
4,Alex Wong,12-06-2001,Male,Sore Throat,Bacterial Infection,Strep Throat,Penicillin
5,Sarah Kim,25-03-1972,Female,"Joint Pain, Fatigue",Rheumatoid Arthritis,Arthritis,NSAIDs
6,David Wu,18-09-1995,Male,"Chest Pain, Dizziness",High Blood Pressure,Hypertension,Amlodipine
7,Olivia Tan,08-07-1987,Female,"Itching, Redness",Allergies,Allergic Reaction,Antihistamine
8,Chris Ng,01-12-1983,Male,"Abdominal Pain, Bloating",Poor Diet,Indigestion,Antacids
9,Samantha Liu,30-04-1998,Female,"Fatigue, Sadness",Depression,Major Depressive,Sertraline

In [99]:
df.to_csv("medical data cleaned.csv",index=False)