In [1]:
import pandas as pd

creating a series

In [2]:
#seies from a list
numbers = [10,20,30,40]
num_series = pd.Series(numbers)
print(num_series)

0    10
1    20
2    30
3    40
dtype: int64

In [3]:
#series with custom index
marks = [85,90,75,60,80,70]
mark_series = pd.Series(marks,index=["Rahul","Anu","John","Alice","Sam","Rohan"])
print(mark_series)

Rahul    85
Anu      90
John     75
Alice    60
Sam      80
Rohan    70
dtype: int64

In [4]:
#series from dictionary
student = {
    "Rahul":85,
    "Anu":90,
    "John":75,
    "Alice":60,
    "Sam":80,
    "Rohan":70
}
student_series = pd.Series(student)
student_series

Rahul    85
Anu      90
John     75
Alice    60
Sam      80
Rohan    70
dtype: int64

In [5]:
#accessing values
mark_series

Rahul    85
Anu      90
John     75
Alice    60
Sam      80
Rohan    70
dtype: int64

In [6]:
#by position
mark_series.iloc[0]

np.int64(85)

In [7]:
#by label
print(mark_series["Rahul"])

85

series properties

In [8]:
#index
print(mark_series.index)

Index(['Rahul', 'Anu', 'John', 'Alice', 'Sam', 'Rohan'], dtype='str')

In [9]:
#values
print(mark_series.values)

[85 90 75 60 80 70]

In [10]:
#data type
mark_series.dtype

dtype('int64')

functions

In [11]:
#sum
print(mark_series.sum())

460

In [12]:
#average
print(mark_series.mean())

76.66666666666667

In [13]:
#maximum
print(mark_series.max())

90

In [14]:
#minimum
print(mark_series.min())

60

In [15]:
#count
print(mark_series.count())

6

In [16]:
#show first value
print(mark_series.head())

Rahul    85
Anu      90
John     75
Alice    60
Sam      80
dtype: int64

In [17]:
#show first 2 values
print(mark_series.head(2))

Rahul    85
Anu      90
dtype: int64

In [18]:
#show last value
print(mark_series.tail())

Anu      90
John     75
Alice    60
Sam      80
Rohan    70
dtype: int64

In [19]:
#show last 2 values
print(mark_series.tail(2))

Sam      80
Rohan    70
dtype: int64

filtering data

In [20]:
#display value greater than 20
a = pd.Series([10,20,30,40,50])
print(a[a>20])

2    30
3    40
4    50
dtype: int64

In [21]:
#updating a value
a[1] = 100
a

0     10
1    100
2     30
3     40
4     50
dtype: int64

In [22]:
#adding new value
a["New"] = 60
a

0       10
1      100
2       30
3       40
4       50
New     60
dtype: int64

In [23]:
#deleting a value
a = a.drop("New")
a

0     10
1    100
2     30
3     40
4     50
dtype: int64

DataFrame

In [24]:
#creating a dataframe
data = {
    "Name":["Rahul","Anu","John","Alice","Sam","Rohan"],
    "Age":[20,21,19,22,20,21],
    "Marks":[85,90,78,82,75,67]
}
df = pd.DataFrame(data)
df

    Name  Age  Marks
0  Rahul   20     85
1    Anu   21     90
2   John   19     78
3  Alice   22     82
4    Sam   20     75
5  Rohan   21     67

In [25]:
#first 5 rows
df.head()

    Name  Age  Marks
0  Rahul   20     85
1    Anu   21     90
2   John   19     78
3  Alice   22     82
4    Sam   20     75

In [26]:
#first 2 rows
df.head(2)

    Name  Age  Marks
0  Rahul   20     85
1    Anu   21     90

In [27]:
#last 5 rows
df.tail()

    Name  Age  Marks
1    Anu   21     90
2   John   19     78
3  Alice   22     82
4    Sam   20     75
5  Rohan   21     67

In [28]:
#last 2 rows
df.tail(2)

    Name  Age  Marks
4    Sam   20     75
5  Rohan   21     67

info about data

In [29]:
#shape
df.shape

(6, 3)

In [30]:
df.columns

Index(['Name', 'Age', 'Marks'], dtype='str')

In [31]:
df.dtypes

Name       str
Age      int64
Marks    int64
dtype: object

info about dataframe

In [32]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    6 non-null      str
 1   Age     6 non-null      int64
 2   Marks   6 non-null      int64
dtypes: int64(2), str(1)
memory usage: 276.0 bytes

statistical info

In [33]:
df.describe()

             Age      Marks
count   6.000000   6.000000
mean   20.500000  79.500000
std     1.048809   8.068457
min    19.000000  67.000000
25%    20.000000  75.750000
50%    20.500000  80.000000
75%    21.000000  84.250000
max    22.000000  90.000000

In [34]:
#select one column
df["Name"]

0    Rahul
1      Anu
2     John
3    Alice
4      Sam
5    Rohan
Name: Name, dtype: str

In [35]:
#select multiple column
df[["Name","Marks"]]

    Name  Marks
0  Rahul     85
1    Anu     90
2   John     78
3  Alice     82
4    Sam     75
5  Rohan     67

accessing rows

In [36]:
#label
df.loc[0]

Name     Rahul
Age         20
Marks       85
Name: 0, dtype: object

In [37]:
#position
df.iloc[2]

Name     John
Age        19
Marks      78
Name: 2, dtype: object

functions

In [38]:
df["Marks"].sum()

np.int64(477)

In [39]:
df["Marks"].mean()

np.float64(79.5)

In [40]:
df["Marks"].max()

np.int64(90)

In [41]:
df["Marks"].min()

np.int64(67)

filtering data

In [42]:
#greater than 80
df[df["Marks"]>80]

    Name  Age  Marks
0  Rahul   20     85
1    Anu   21     90
3  Alice   22     82

In [43]:
#adding new column
df["Grade"]=["B","A","C","B","C","C"]
df

    Name  Age  Marks Grade
0  Rahul   20     85     B
1    Anu   21     90     A
2   John   19     78     C
3  Alice   22     82     B
4    Sam   20     75     C
5  Rohan   21     67     C

In [44]:
#deleting a column
df = df.drop("Grade",axis=1)
df

    Name  Age  Marks
0  Rahul   20     85
1    Anu   21     90
2   John   19     78
3  Alice   22     82
4    Sam   20     75
5  Rohan   21     67

In [45]:
#saving dataframe
df.to_csv("students.csv",index=False)

data selection using loc & iloc

In [46]:
import pandas as pd
data = {
    "Name":["Asha","Rahul","Anu"],
    "Age":[20,21,19],
    "City":["Kochi","Delhi","Chennai"]
}
df = pd.DataFrame(data)
print(df)

    Name  Age     City
0   Asha   20    Kochi
1  Rahul   21    Delhi
2    Anu   19  Chennai

In [47]:
#loc row label
print(df.loc[1])

Name    Rahul
Age        21
City    Delhi
Name: 1, dtype: object

In [48]:
#loc row and column label
print(df.loc[0:1,["Name","Age"]])

    Name  Age
0   Asha   20
1  Rahul   21

In [49]:
# iloc row label
print(df.iloc[1])

Name    Rahul
Age        21
City    Delhi
Name: 1, dtype: object

In [50]:
#iloc row and column label
print(df.iloc[0:2,0:2])

    Name  Age
0   Asha   20
1  Rahul   21

difference in slicing

In [51]:
#loc 
print(df.loc[0:1])

    Name  Age   City
0   Asha   20  Kochi
1  Rahul   21  Delhi

In [52]:
#iloc
print(df.iloc[0:1])

   Name  Age   City
0  Asha   20  Kochi

selecting a single value

In [53]:
#loc
print(df.loc[2,"City"])

Chennai

In [54]:
#iloc
print(df.iloc[2,2])

Chennai

Data Integration and Transformation

In [55]:
#Basic Merging
import pandas as pd
df1 = pd.DataFrame({
    "id":[1,2,3],
    "name":["Asha","Binu","Cathy"]
})
df2 = pd.DataFrame({
    "id":[1,2,4],
    "marks":[85,90,75]
})
merged_df = pd.merge(df1,df2,on="id")
print(merged_df)

   id  name  marks
0   1  Asha     85
1   2  Binu     90

Types of Joins

In [56]:
#inner join
pd.merge(df1,df2,on = "id",how="inner")

   id  name  marks
0   1  Asha     85
1   2  Binu     90

In [57]:
#left join
pd.merge(df1,df2,on="id",how="left")

   id   name  marks
0   1   Asha   85.0
1   2   Binu   90.0
2   3  Cathy    NaN

In [58]:
#right join
pd.merge(df1,df2,on="id",how="right")

   id  name  marks
0   1  Asha     85
1   2  Binu     90
2   4   NaN     75

In [59]:
#outer join
pd.merge(df1,df2,on="id",how="outer")

   id   name  marks
0   1   Asha   85.0
1   2   Binu   90.0
2   3  Cathy    NaN
3   4    NaN   75.0

Merge on different column names

In [60]:
import pandas as pd
df1 = pd.DataFrame({
    "id":[1,2,3],
    "name":["Asha","Binu","Cathy"]
})
df2 = pd.DataFrame({
    "student_id":[1,2,4],
    "marks":[85,90,75]
})
merged_df =  pd.merge(df1,df2,left_on="id",right_on="student_id")
merged_df

   id  name  student_id  marks
0   1  Asha           1     85
1   2  Binu           2     90

concatenation

In [61]:
#row wise
pd.concat([df1,df2],axis = 0)

    id   name  student_id  marks
0  1.0   Asha         NaN    NaN
1  2.0   Binu         NaN    NaN
2  3.0  Cathy         NaN    NaN
0  NaN    NaN         1.0   85.0
1  NaN    NaN         2.0   90.0
2  NaN    NaN         4.0   75.0

In [62]:
#column wise
pd.concat([df1,df2],axis=1)

   id   name  student_id  marks
0   1   Asha           1     85
1   2   Binu           2     90
2   3  Cathy           4     75

Apply

In [63]:
import pandas as pd 
marks = pd.Series([45,60,75,90])
def grade(x):
    if x >= 50:
        return"Pass"
    else:
        return"Fail"
print(marks.apply(grade))

0    Fail
1    Pass
2    Pass
3    Pass
dtype: str

Apply using Lambda Function

In [64]:
import pandas as pd
marks = pd.Series([45,60,75,90])
result = marks.apply(lambda x: x + 5)
print(result)

0    50
1    65
2    80
3    95
dtype: int64

Apply on DataFrame columns

In [65]:
import pandas as pd
df = pd.DataFrame({
    "Math":[80,70,90],
    "Science":[85,60,95]
})
print(df.apply(max))

Math       90
Science    95
dtype: int64

In [74]:
# merge with same column name
import pandas as pd
f1 = pd.DataFrame({
    "Id":[1,2,3,4,5],
    "Name":["John","Rahul","Tiya","Rohan","Alia"],
    "Course":["Python","Flutter","Python","Data Science","Flutter"]
})
f2 = pd.DataFrame({
    "Id":[1,2,3,6,7],
    "Marks":[80,94,78,70,90],
    "Duration":["6 mnth","4 mnth","6 mnth","4 mnth","6 mnth"]
})
merged = pd.merge(f1,f2, on="Id")
print(merged)

   Id   Name   Course  Marks Duration
0   1   John   Python     80   6 mnth
1   2  Rahul  Flutter     94   4 mnth
2   3   Tiya   Python     78   6 mnth

In [68]:
pd.merge(f1,f2,on="Id",how="inner")

   Id   Name   Course  Marks Duration
0   1   John   Python     80   6 mnth
1   2  Rahul  Flutter     94   4 mnth
2   3   Tiya   Python     78   6 mnth

In [69]:
pd.merge(f1,f2,on="Id",how="left")

   Id   Name        Course  Marks Duration
0   1   John        Python   80.0   6 mnth
1   2  Rahul       Flutter   94.0   4 mnth
2   3   Tiya        Python   78.0   6 mnth
3   4  Rohan  Data Science    NaN      NaN
4   5   Alia       Flutter    NaN      NaN

In [70]:
pd.merge(f1,f2,on="Id",how="right")

   Id   Name   Course  Marks Duration
0   1   John   Python     80   6 mnth
1   2  Rahul  Flutter     94   4 mnth
2   3   Tiya   Python     78   6 mnth
3   6    NaN      NaN     70   4 mnth
4   7    NaN      NaN     90   6 mnth

In [71]:
pd.merge(f1,f2,on="Id",how="outer")

   Id   Name        Course  Marks Duration
0   1   John        Python   80.0   6 mnth
1   2  Rahul       Flutter   94.0   4 mnth
2   3   Tiya        Python   78.0   6 mnth
3   4  Rohan  Data Science    NaN      NaN
4   5   Alia       Flutter    NaN      NaN
5   6    NaN           NaN   70.0   4 mnth
6   7    NaN           NaN   90.0   6 mnth

In [75]:
# merge with diff column name
import pandas as pd
f11 = pd.DataFrame({
    "Id":[1,2,3,4,5],
    "Name":["John","Rahul","Tiya","Rohan","Alia"],
    "Course":["Python","Flutter","Python","Data Science","Flutter"]
})
f22 = pd.DataFrame({
    "Number":[1,2,3,6,7],
    "Marks":[80,94,78,70,90],
    "Duration":["6 mnth","4 mnth","6 mnth","4 mnth","6 mnth"]
})
merged1 = pd.merge(f11,f22,left_on="Id",right_on="Number")
merged1

   Id   Name   Course  Number  Marks Duration
0   1   John   Python       1     80   6 mnth
1   2  Rahul  Flutter       2     94   4 mnth
2   3   Tiya   Python       3     78   6 mnth